### PR TITLE
CHANGELOG: add missing entries

### PR DESCRIPTION
**Pull request by woodruffw**
This was my fault; kept forgetting to update these.

### CODE REVIEW

**Review by facutuesca — APPROVED** [review]
LGTM!

**Comment by woodruffw** [comment]
Hmm, not sure why the CI isn't running on PRs anymore.

**Comment by facutuesca** [comment]
> Hmm, not sure why the CI isn't running on PRs anymore.

Maybe a GHA temporary issue? I see that yesterday they did run: https://github.com/trailofbits/pypi-attestations/actions/runs/9698901618/job/26766574609

**Comment by woodruffw** [comment]
Ah yeah, looks like it was just slow for some reason.

**Comment by DarkaMaul** [comment]
I forgot too about the CHANGELOG.
I will keep it it in mind for future PR.

**Pull request merged**
